### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by juddey** [echobind/paranoid#2]
```
warning: non-atom keys in cast/3 is deprecated. All keys must be atoms, got: `"deleted_at"`
  (ecto) lib/ecto/changeset.ex:552: Ecto.Changeset.cast_key/1
  (ecto) lib/ecto/changeset.ex:515: Ecto.Changeset.process_param/7
  (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ecto) lib/ecto/changeset.ex:501: Ecto.Changeset.cast/6
```
I'll PR this issue, when I get sick of the warnings in my console.... :wink: 

If anyone else wants to have a go, feel free :smile:

**Comment by D4no0** [comment]
https://github.com/echobind/paranoid/pull/3

**Comment by mauricionr** [comment]
we can close this issue?

**Comment by D4no0** [comment]
With the PR: https://github.com/echobind/paranoid/pull/3, I updated the string keys to atom ones, so yeah.

**Comment by juddey** [comment]
Closed.
